name: CI Pipeline Web3 Smart Contract

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./smart_contract
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          IGNORE_GITIGNORED_FILES: true
          DISABLE_ERRORS: true ##Dont use in production environment!!!!!
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

  smart-contract-build:
    name: Build Smart Contract Code
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: ./smart_contract
    strategy:
      matrix:
        node-version: [18.x]
        architecture: [x64]
    steps:
      - name: Check-out Code  
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js ${{ matrix.node-version }} - ${{ matrix.architecture }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies 
        run: npm ci
        env:
          CI: true

      - name: Build
        run: npx hardhat compile

  sonarcloud:
    name: SonarCloud Quality Gate
    runs-on: ubuntu-latest
    needs: smart-contract-build
    defaults:
      run:
        working-directory: ./smart_contract
    steps:
      - name: Check-out Code  
        uses: actions/checkout@v4.1.7

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v8

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: smart_contract
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.host.url=${{ secrets.SONAR_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=contracts/,scripts/
            -Dsonar.verbose=true

  docker_image:
    name: Build, Scan and push Smart Contract Docker Image to ECR
    runs-on: ubuntu-latest
    needs: sonarcloud
    defaults:
      run:
        working-directory: ./smart_contract
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_SMART_CONTRACT_REPOSITORY_NAME }}
          IMAGE_TAG: 0.1.0
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Snyk Docker image vulnerability scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.image }}
        continue-on-error: true ##Dont use in production environment!!!!!

      - name: Trivy Docker image vulnerability scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ env.image }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true ##Dont use in production environment!!!!!

      - name: Push into ECR
        run: docker push ${{ env.image }}